
;**********************************************
; 318045-01 ROM    03/20/87   F.BOWEN    $8E8B
;**********************************************

	.include "mfmmacro.asm"
	.include "common.asm"
	.include "equate.asm"
	.include "iodef.asm"
	.include "ram.asm"
	.include "dversion.asm"	;checksum, signature, & version bytes
	.include "parsex.asm"
	.include "setdrv.asm"
	.include "lookitup.asm"
	.include "trnsfr.asm"
	.include "scrtch.asm"
	.include "formatd.asm"
	.include "copy.asm"
	.include "rename.asm"
	.include "memrw.asm"
	.include "blk.asm"
	.include "fndrel.asm"
	.include "tst2.asm"
	.include "tst3.asm"
	.include "tst4.asm"
	.include "tst5.asm"
	.include "job.asm"
	.include "addfil.asm"
	.include "open.asm"
	.include "close.asm"
	.include "opchnl.asm"
	.include "tstflg.asm"
	.include "tsutil.asm"
	.include "ssutil.asm"
	.include "sstest.asm"
	.include "getact.asm"
	.include "rel1.asm"
	.include "rel2.asm"
	.include "rel3.asm"
	.include "rel4.asm"
	.include "ssend.asm"
	.include "record.asm"
	.include "nulbuf.asm"
	.include "addrel.asm"
	.include "newss.asm"
	.include "system.asm"
	.include "erproc.asm"
	.include "utlodr.asm"
	.include "utl.asm"
	.include "signature.asm"
	.include "sieee.asm"
	.include "dskint.asm"
	.include "idle.asm"
	.include "lstdir.asm"
	.include "verdir.asm"
	.include "newdsk.asm"
	.include "mapit.asm"
	.include "frets.asm"
	.include "bamutl.asm"
	.include "tstfnd.asm"
	.include "part.asm"
	.include "fastld.asm"
	.include "burstc.asm"
	.include "mcntl.asm"
	.include "mrout.asm"
	.include "msub.asm"
	.include "msub1.asm"
	.include "crc.asm"
	.include "irq.asm"
	.include "romtbl.asm"
	.include "relnotes.asm"
	.include "patch.asm"
	.include "vects.asm"

